### ISSUE TITLE
Getting "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value"

### ISSUE THREAD

**Issue by davidpdrsn** [qmx/cpubars#1]
Not quite sure if this is ready to use yet, but I'm getting this error:

```
❯ cargo install cpubars
...

❯ cpubars
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /Users/david/.cargo/registry/src/github.com-1ecc6299db9ec823/cpubars-0.4.3/src/main.rs:31:14
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: cpubars::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

❯ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/david/.rustup

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.42.0 (b8cedc004 2020-03-09)
```

**Comment by qmx** [comment]
Yea, this is linux-only 😞   (I'm using `/proc/*` for getting the cpu usage)

I do want to eventually make it cross-platform, I'll investigate how to make that happen this week. Sorry for the trouble!

**Comment by qmx** [comment]
So I've found [a crate](https://docs.rs/psutil) that fixes the cross-platform problem, going to try to get this implemented soon!

Thanks for reporting!

**Comment by qmx** [comment]
I've pushed a fix at 164a64f1e02d123823319379da394d0133ad7c63 - could you please give it a try?

**Comment by davidpdrsn** [comment]
That seems to have fixed it. I get this now while compiling a big crate from scratch

![image](https://user-images.githubusercontent.com/718941/77529141-63163580-6e8f-11ea-8d9d-257bdeacf351.png)

Thanks!

**Comment by qmx** [comment]
Yay! I'll figure out how to make OSX binaries and cut a release soon. Thanks for reporting it!

**Comment by qmx** [comment]
welp, I should have cut a release for this, doing it now!

**Comment by qmx** [comment]
v0.5.0 released
